# Generated by Django 5.2.8 on 2025-11-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_cv_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
